version: '3'
services:
  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_lec_production
    ports:
      - "5432:5432"
  
  web:
    build: .
    entrypoint: ./entrypoint.sh
    command: rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      DATABASE_HOST: db
      RAILS_ENV: production

volumes:
  pg_data:
